[theme]

# Primary accent for interactive elements
primaryColor = '#48B2E8'

# Background color for the main content area
backgroundColor = "#F6F8FC"

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#FFFFFF'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"